package Hack4LA::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Hack4LA::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:hack4la',
        user => 'max',
        password => 'cabral',
    }
);

=head1 NAME

Hack4LA::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Hack4LA>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Hack4LA::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Grigor Karavardanyan

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
